DTC_INCLUDE += $(srctree)/../sm6225-modules/qcom/opensource/camera-kernel
KBUILD_DTC_INCLUDE += $(srctree)/../sm6225-modules/qcom/opensource/camera-kernel

include $(srctree)/$(src)/config/holi.mk

always-y	:= $(dtbo-y) $(dtb-y)
subdir-y	:= $(dts-dirs)
clean-files	:= *.dtb *.dtbo
